### PR TITLE
Add section about Presto: The Definitive Guide

### PR DESCRIPTION
**Pull request by mosabua**
I am an author of this book and believe it provides great information for all Presto users.

### CODE REVIEW

**Comment by dborkar** [comment]
@mosabua Thx. Appreciate your contribution. Looking at the links and the book, it is based on prestosql (a different repo). Given the difference in the repos, it will be very confusing for users and the community if a technical resource that is based on a different repo gets added in. Unfortunately because of this, we will not be able to accept this PR. 

image

**Comment by dborkar** [comment]
@nezihyigitbasi FYI

**Comment by mosabua** [comment]
The book covers Presto and everything readers learn from it  applies to both Presto versions. I strongly believe that users should get the useful tips from the book no matter what open source Presto version they choose. I would encourage you to merge the PR for the benefit of all Presto users.

**Comment by mosabua** [comment]
@dborkar @nezihyigitbasi .. any update?

**Pull request closed without merging**
