### PR TITLE
Introduce gh-pages and deployment via Travis & Docusarus

### PR DESCRIPTION
**Pull request by aweisberg**
I refactored the site to be deployed by the Docusaurus deployment process and Travis. This simplifies deploying changes to the blog. All the static content from the site as well as any files that should exist on the master branch are stored under website/static.

This would merge to a gh-pages branch (can't create a PR to a non-existent branch) and Travis would then publish the site to master.

Unfortunately I had to move the docs under website/static instead of using a symlink because when Docusaurus publishes it won't copy the contents of a symlink it just copies the symlink.

Fixes: #27

### CODE REVIEW

**Comment by aweisberg** [comment]
This is "done" modulo review. I propose we merge once we have our first blog post.

I will update one or two configs values in siteConfig.js to match the baseUrl and project name of Presto. Right now this is deployed to my github and building.

https://aweisberg.github.io/prestodb.github.io/
https://travis-ci.com/aweisberg/prestodb.github.io
https://github.com/aweisberg/prestodb.github.io/commits/master

**Comment by JoelMarcey** [comment]
cc @yangshun

@aweisberg - 65K files changes is a lot 😄 -- I assume you meant to have all those `/docs/0.110/...` path changes.

**Comment by yangshun** [comment]
Yes @aweisberg's way was to put the existing HTML content into the `static` dir which would be copied during deployment. That's a smart way 😄

**Comment by JoelMarcey** [comment]
Screenshot 2019-06-19 13 33 20

You meant to delete these from the root?

**Comment by aweisberg** [comment]
I moved them to website/static and then created links to them in the root of the gh-pages branch. They are copied onto master when Docusaurus deploys.

**Comment by JoelMarcey** [comment]
Ah right - I forgot this was a github.io repo.

**Pull request merged**
