### PR TITLE
Migrate to Docusaurus

### PR DESCRIPTION
**Pull request by ggreg**
## Description

This is a work-in-progress version to migrate the website to [Docusaurus](https://docusaurus.io). The two main motivation are:
1. Ease of edition
2. Adding a blog for news and announcements

## TODO

- [ ] References reference documentation of releases (and update `presto-docs.sh`)
- [ ] Adding missing sections:
  - [ ] Community
  - [ ] Resources
  - [ ] Development
- [ ] Get approval from companies using Presto
- [ ] Add first post to blog
- [ ] Document how to edit and build the static site with Docusaurus in the `README`

### CODE REVIEW

**Comment by ggreg** [comment]
prestodb-docusaurus-wip

**Comment by caniszczyk** [comment]
docusaurus is being used already

**Comment by aweisberg** [comment]
We are only using it for the blog. It's causing the style not to match across the site (the docs already didn't match).

It's a mess.

**Comment by caniszczyk** [comment]
ah I will reopen then, sorry about that, was my misunderstanding

**Pull request closed without merging**
