### PR TITLE
Initial stab at using Docusarus for just the blog

### PR DESCRIPTION
**Pull request by aweisberg**
Closes: #27

### CODE REVIEW

**Comment by aweisberg** [comment]
What it currently looks like without styling
image
image

**Comment by JoelMarcey** [comment]
@yangshun @endiliey -- Can you also have a look at this, particularly from a design perspective?

**Comment by yangshun** [comment]
Design looks fine, but not sure if you want to commit the build artifacts into the repo or let the build process run after every merge.

**Comment by aweisberg** [comment]
I spent some time trying to rework the style and didn't have enough luck to make it seem worthwhile. I'm going to work on getting automated deployment working on my fork.

**Comment by JoelMarcey** [comment]
From my end, I agree with @yangshun - I think the design looks fine as-is. For many Docusaurus blogs, the design is pretty minimal.

**Comment by aweisberg** [comment]
Closing in favor of https://github.com/prestodb/prestodb.github.io/pull/29 which automates deployment of the blog.

**Pull request closed without merging**
