### PR TITLE
merge to new branch (#3)

### PR DESCRIPTION
**Pull request by mcknightd**
* squashed previous commits
* Added Alibaba to Prestocon Banner

### CODE REVIEW

**Comment by aweisberg** [comment]
Can you clean up that commit message? It looks like it has a lot of extra stuff in it?

**Comment by mcknightd** [comment]
I have amended the commit message

**Comment by aweisberg** [comment]
Sorry can you also clean up the commit history so that it's just 1 commit and not a merge commit?

It should just be one commit with a message saying something like "Add Alibaba to prestocon banner"

**Comment by mcknightd** [comment]
I'll close this and try again

**Pull request closed without merging**
