### PR TITLE
add quix to list of presto UIs

### PR DESCRIPTION
**Pull request by frolovv**

### CODE REVIEW

**Comment by aweisberg** [comment]
Thanks for this. I'll look at it Monday.

**Comment by aweisberg** [comment]
@frolovv Is this compatible with PrestoDB? All the docs in the Quix repo link to PrestoSQL as does the docker container in the example.

**Comment by frolovv** [comment]
@aweisberg it's compatible with prestodb, internally we are using prestodb and not prestosql.

regarding localhost issues, take a look at : https://github.com/wix/quix/issues/116
it's probably docker-related

**Comment by aweisberg** [comment]
TY looks like a useful tool.

**Pull request merged**
