### PR TITLE
0.288.1 docs

### PR DESCRIPTION
**Pull request by wanglinsong**

### CODE REVIEW

**Comment by wanglinsong** [comment]
@steveburnett please confirm docs has the correct link to the presto-server tgz file.

**Comment by steveburnett** [comment]
> @steveburnett please confirm docs has the correct link to the presto-server tgz file.

@wanglinsong, are you referring to the "Manual/Local Download" pane (the upper left of the four download panes) on this branch's updated page replacing https://prestodb.io/getting-started/ on the website? I don't see any of the download panes in my local  file:

See screenshot showing 0.288.1 and no download panes. 
Screenshot 2024-08-15 at 2 25 24 PM

.
.
.
In the docs, in installation/deployment.html, the link to presto-server-0.288.1.tar.gz is correct: I successfully downloaded presto-server-0.288.1.tar.gz from that page (see screenshot): 
Screenshot 2024-08-15 at 2 32 07 PM

**Comment by wanglinsong** [comment]
the getting started page. please check the tgz file has the presto-ui jar included.

**Comment by steveburnett** [comment]
> the getting started page. please check the tgz file has the presto-ui jar included.

As shown in the first screenshot in [my comment](https://github.com/prestodb/prestodb.github.io/pull/278#issuecomment-2291953430), the Getting Started page does not have download links at all. 

The tgz file that I downloaded from the link on installation/deployment.html has the file `presto-ui-0.288.1.jar` included.

**Comment by wanglinsong** [comment]
This release has nothing to do with the getting started page.
Were there any updates for that page?
@alileclerc

**Review by steveburnett — APPROVED** [review]
LGTM! (docs)

As @wanglinsong requested I check, the presto-server-0.288.1.tar.gz file that I downloaded from the link on installation/deployment.html has the file presto-ui-0.288.1.jar included.

The 0.288.1 Release Notes page is included in the doc update.

**Comment by steveburnett** [comment]
> This release has nothing to do with the getting started page. Were there any updates for that page? @alileclerc

Okay, then I won't worry about the Getting Started page looking odd as shown in the screenshot. 

The 0.288.1 release notes are where they should be in the doc, and the the presto-server-0.288.1.tar.gz file that I downloaded from the link on installation/deployment.html has the file presto-ui-0.288.1.jar included, so reviewed and approved.

**Comment by yhwang** [comment]
FYI, @wanglinsong my previous PR is not merged yet #277 
Landing this PR will remove the old archived releases since I only manually added them to the master branch earlier.

**Review by tdcmeehan — APPROVED** [review]

**Pull request merged**
