### PR TITLE
Create 2020-11-30-prestocon-and-foundation-update.md

### PR DESCRIPTION
**Pull request by gbbaliga**
Foundation and PrestoCon updates, and welcome new foundation members.

### CODE REVIEW

**Comment by gbbaliga** [comment]
Please review and merge @aweisberg, @dborkar. Thanks!

**Comment by dborkar** [comment]
The blog is already reviewed by multiple people on the board and LF. 

@gbbaliga can you please add the truncate under the first paragraph. I’ll merge in after. Thx

**Comment by dborkar** [comment]
@gbbaliga

**Comment by gbbaliga** [comment]
@dborkar, added a summary and truncate at the beginning of the post. Please review and commit. Thanks!

**Comment by dborkar** [comment]
Thank you @gbbaliga. Merging in now.

**Pull request merged**
