### PR TITLE
add a new 3rd-party tutorial

### PR DESCRIPTION
**Pull request by apc999**
Screenshot:
Screen Shot 2020-06-24 at 11 02 22 AM

Add a new piece of quick start here,non-docker and using Presto+HiveMetastore on a local laptop

### CODE REVIEW

**Comment by apc999** [comment]
@aweisberg can you help take a look? thanks

**Comment by aweisberg** [comment]
This tutorial stopped working at this command
```
aweisberg-mbp:alluxio-2.2.2 aweisberg$ bin/alluxio fs mount --readonly /example \
>    s3://apc999/presto-tutorial/example-reason/

com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
```

More generally I am troubled that we are linking to external vendor documentation instead having people contribute improvements to the OSS project's documentation. @brianwarner @dborkar 

IMO the OSS Presto web site should be vendor neutral. It's difficult to maintain neutrality when links to documentation are on a vendor's web site. When can vendor A replace vendor B's documentation with something they think is "better?" It also fragments the documentation.

Vendors are an important part of the community and we definitely need to make them successful for the OSS project to be successful. We should be showcasing what vendors have to offer, but in a way that doesn't cede control or lead to conflicts over the contents of the web site.

Ceding control is a risk to the long term health of the project and something that can have serious fallout if it needs to be corrected later. It's not safe to assume that the set of vendors in the community or relationships/behavior of those vendors will be stable over time.

**Comment by aweisberg** [comment]
Some other issues, it creates a ramdisk, alluxio-stop requires sudo, that also generates errors
```
aweisberg-mbp:bin aweisberg$ sudo ./alluxio-stop.sh all
Error: Alluxio requires Java 8, currently Java 12 found.
Error: Alluxio requires Java 8, currently Java 12 found.
Error: Alluxio requires Java 8, currently Java 12 found.
Error: Alluxio requires Java 8, currently Java 12 found.
Error: Alluxio requires Java 8, currently Java 12 found.
Error: Alluxio requires Java 8, currently Java 12 found.
```

**Comment by apc999** [comment]
@aweisberg  thanks for the comments. I will rewrite the quick start in my personal blog rather then the existing corp blog to both make this vendor-neutral as well as have the technical suggestions addressed. Will submit the PR later today or tomorrow.

**Comment by apc999** [comment]
Update the PR pointing to [my medium post](https://medium.com/@binfan_alluxio/running-presto-with-hive-metastore-on-a-laptop-in-10-minutes-72823f1ebf01), and also refactored the tutorial to just talk about Presto and Hive. 
Feel free to check it again and let me know if there is any issue you found @aweisberg 

@dborkar @achopragh the discussion was not complete before the meeting ended and there were still proposals to keep content from third party on this page for a short while. Though I am totally aligned with the direction to keep the getting-started page vendor free. 

Given more content is very helpful in the near term, I'd like see other folks' reaction---at least I believe this is a useful piece of content to help the community user to quickly get started on their local laptop. Feel free to chime in if you have different views.

**Comment by aweisberg** [comment]
That's quite a few steps :-) I don't have time to test it out, but I found several instances of missing whitespace. It's hard to review it because it's not a pull request agains the web site or documentation (hint hint) ;-)

I hate to keep asking, but why are we linking to external sites like medium and not to our own blog or documentation?

How does this serve the project or the community better by being on an externally hosted web site without version history where it can't be maintained by any of the committers?

**Comment by dborkar** [comment]
@apc999 this is a nice tutorial for a very common use case for Presto. I agree with @aweisberg. It would be great to add this to the documentation. It would be great to have a public s3 bucket for the project given the tutorial uses some sample data from S3. @aweisberg are you aware of a public account that already exists? 

I suggest adding a new subsection to the "Installation section" https://prestodb.io/docs/current/installation.html

**Comment by aweisberg** [comment]
I am not aware of an S3 bucket for the project.

**Pull request closed without merging**
