### PR TITLE
prestocon day 2021 on-demand page

### PR DESCRIPTION
**Pull request by mcknightd**
Second attempt at creating PR... first one had yarn issue.

image

image

### CODE REVIEW

**Comment by mcknightd** [comment]
Let me know if I need to do something about the failed Test Build checks.

**Comment by mcknightd** [comment]
@aweisberg Any ideas what is going wrong with this PR failing the check on yarn run?

**Review by aweisberg — APPROVED** [review]
Would be nice to see the images go into a subdir for the prestoconday2021 just so this scales, but the web site probably won't last another year so ???

The PR check doesn't work. Let me give a whirl to see if I can fix it I have been ignoring it for too long. You can merge without it.

It worked when I looked at it.

**Comment by dborkar** [comment]
Merging this in given comment above from @aweisberg  
@mcknightd please double check site once merged given the issue we were seeing earlier.

**Pull request merged**
